### ISSUE TITLE
K64F doesn't work

### ISSUE THREAD

**Issue by ccli8** [ARMmbed/mbed-os-example-uvisor-thread#10]
**mbed-os sha**
mbed-os-5.1.0
**GCC ARM version**
4.9.3
**Target board**
K64F
**Steps to Reproduce**
Build and drag-n-drop the built binary onto K64F, but no printf message and no LED blinking.

```
$ mbed compile -m K64F -t GCC_ARM
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2852

**Comment by ccli8** [comment]
Fixed in 357ca9b1d4afbe9609efa1bbc3c8a4408e7121af.
