### ISSUE TITLE
uVisor example code does not work out-of-the-box for the FRDM K64F target

### ISSUE THREAD

**Issue by sherrellbc** [ARMmbed/mbed-os-example-uvisor-thread#11]
The uVisor example is not properly working for the [FRDM K64F](https://developer.mbed.org/platforms/FRDM-K64F/) development board.

When deployed to the board I observe exactly nothing -- no blinky LEDs, no serial output. I can get simple blinky code to work without issue -- it is only when uVisor is enabled that things seem to break. 

Are there implied instructions not mentioned in the short guide? I have spent several days researching this problem only to find very little. I feel like this is not an appropriate place for troubleshooting, but I am convinced there must be something wrong with the reference code.

Can someone confirm this works without modification?

**Comment by sherrellbc** [comment]
Confirmed to worked without modification at 357ca9b1d.

See #10 

---

Commit cfb43b81a968ac breaks the example code by updating to mbed-os-5.1.2. I submitted a pull request to patch the blinky code. 

https://github.com/ARMmbed/uvisor/pull/314

**Comment by meriac** [comment]
@sherrellbc Can you please retry the latest master ? I updated the .lib in this example with the latest mbed-os master. I can confirm that it works for me (compiling without warning and executing with blinky cycle)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2872

**Comment by sherrellbc** [comment]
@meriac, I can confirm that the example now works on master. 

Although, my other problem related to the actual uVisor code not liking SVC calls is not fixed with the update,  albeit unrelated to this specific problem. 

https://github.com/ARMmbed/uvisor/issues/315
