### ISSUE TITLE
uVisor quick start guide does not work

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-os-example-uvisor-thread#17]
https://docs.mbed.com/docs/uvisor-and-uvisor-lib-documentation/en/latest/quick_start/#the-main-box-acls

Compile the RTOS example as mentioned there on K64F: board segfaults.

Also it would be nice to have pyOCD instructions instead of JLink for debugging.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2929

**Comment by AlessandroA** [comment]
This should be now fixed.
