### ISSUE TITLE
Runtime execution fails when built with make_gcc_arm exporter

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-os-example-uvisor-thread#39]
I believe this is a known issue (https://jira.arm.com/browse/IOTMORF-510). However this was listed in the OOB as a test configuration. @AlessandroA Can you can confirm that this is a known issue/a bad configuration?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-302

**Comment by AlessandroA** [comment]
Hi Brian, yes, this is a known issue. I've updated the README in all 3 repos. I'm also updating the OOB spreadsheet.
