### ISSUE TITLE
Fix tag to mbed-os.lib

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-uvisor-thread#5]
`mbed-os.lib` has to point to the EPR release asap (Sam to provide this info).
At the moment it points to a private copy:
https://github.com/ARMmbed/mbed-os-example-uvisor/blob/master/mbed-os.lib

@AlessandroA @meriac @sg-

**Comment by AlessandroA** [comment]
Hi @mlnx, currently ARMmbed/mbed-os points to mbedmicro/mbed@26e9aa4, while this app needs at least mbedmicro/mbed@9197f94 to work (following [this bug](https://github.com/mbedmicro/mbed/commit/0392b7dea8d1524e242d2fcd02ae7a623b9b80e8) fixed today). @sg- / @0xc0170 please let me know when I can update this reference.

**Comment by 0xc0170** [comment]
done, the master and release branch contains new reference

**Comment by AlessandroA** [comment]
@0xc0170 Shall I target the release tag `mbed-os-5.0.1-epr`?

**Comment by AlessandroA** [comment]
(or the SHA directly?)

**Comment by ghost** [comment]
SHA directly.

**Comment by AlessandroA** [comment]
Done: a25543242f163e956145465785f7f70255fe6ded.

Closing this issue.
