### ISSUE TITLE
[K64F] Crash with adjustment of stack size

### ISSUE THREAD

**Issue by ccli8** [ARMmbed/mbed-os-example-uvisor-thread#55]
### Environment
Target: K64F
Toolchain: gcc 5.4 2016q3
mbed-os-example-uvisor-thread: 979b9f997a27e1f83084797ab62a748f1d53582c
mbed-os: ee864cdd7ba16e69352822da9f270c0b2c056cfe

### Reproduce
For my development, I change mbed-os to version above. Without other modification, I get terminal message below. This is OK.
```
***** Threaded blinky uVisor example *****
Main loop count: 0
Main loop count: 1
Main loop count: 2
Main loop count: 3
Main loop count: 4
Main loop count: 5
Main loop count: 6
Main loop count: 7
Main loop count: 8
Main loop count: 9
Main loop count: 10
Main loop count: 11
```
But after I modify stack size of led3 box main thread from *1024* to *2048*, I get no terminal message.
**led3.cpp**
<pre>
UVISOR_BOX_NAMESPACE(NULL);
UVISOR_BOX_HEAPSIZE(2 * 1024);
UVISOR_BOX_MAIN(led3_main, osPriorityNormal, <b>2048</b>);
UVISOR_BOX_CONFIG(box_led3, acl, 512, box_context);
</pre>

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-381

**Comment by ccli8** [comment]
Answer my own question. The issue is the same as #27 I reported before. Box main thread stack is allocated from box heap. So to fix the issue, box heap size also needs to be enlarged.
<pre>
UVISOR_BOX_NAMESPACE(NULL);
UVISOR_BOX_HEAPSIZE(<b>2 * 1024</b>);
UVISOR_BOX_MAIN(led3_main, osPriorityNormal, <b>2048</b>);
UVISOR_BOX_CONFIG(box_led3, acl, 512, box_context);
</pre>
