### ISSUE TITLE
osThreadContextNew fails with NULL

### ISSUE THREAD

**Issue by ccli8** [ARMmbed/mbed-os-example-uvisor-thread#58]
## Environment

- Target: K64F
- Toolchain: gcc 5.4 2016q3
- mbed-os-example-uvisor-thread: mbed-os-5.5.1 (6fcaba1685528512cab1dc329ab7a7cbce8b07d9)
- mbed-os: mbed-os-5.5.1 (c9e63f14085f5751ff5ead79a7c0382d50a813a2)

## Reproduce

In `source/led3.cpp` > `led3_main`, the call to `osThreadContextNew` fails with NULL. After checking into `mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_thread.c` > `svcRtxThreadNew`, the parameters passed to `osThreadContextNew` are incorrect. These parameters:
<pre>
osThreadAttr_t thread_attr = {0};
os_thread_t thread_def = {0};
<b>thread_def.stack_size = 512;</b>
/* Allocate the stack inside the page allocator! */
thread_attr.stack_mem = (uint32_t *) secure_malloc(alloc, 512);
<b>thread_def.priority = osPriorityNormal;</b>
thread_attr.cb_size = sizeof(thread_def);
thread_attr.cb_mem = &thread_def;
/* Create a thread with the page allocator as heap. */
osThreadContextNew(run_3_context, NULL, &thread_attr, alloc);
</pre>
Should be corrected as:
<pre>
osThreadAttr_t thread_attr = {0};
os_thread_t thread_def = {0};
<b>thread_attr.stack_size = 512;</b>
/* Allocate the stack inside the page allocator! */
thread_attr.stack_mem = (uint32_t *) secure_malloc(alloc, 512);
<b>thread_attr.priority = osPriorityNormal;</b>
thread_attr.cb_size = sizeof(thread_def);
thread_attr.cb_mem = &thread_def;
/* Create a thread with the page allocator as heap. */
osThreadContextNew(run_3_context, NULL, &thread_attr, alloc);
</pre>

This can be proved by checking implementation of `svcRtxThreadNew`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-386
