### ISSUE TITLE
[OOB 5.7][K64F] Pressing SW3 breaks program

### ISSUE THREAD

**Issue by yennster** [ARMmbed/mbed-os-example-uvisor-thread#82]
### Description

- Type: Bug
- Priority: Minor

## Bug
**Target:**
K64F

**Toolchain:**
GCC_ARM

**Toolchain version:**
```
$ ${HOME}/opt/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors 6-2017-q2-update) 6.3.1 20170620 (release) [ARM/embedded-6-branch revision 249437]
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**mbed-cli version:**
1.2.0

**mbed-os sha:**
mbed-os-example-uvisor-thread (aa1369285e5f99f3bb6e0a888f66041a0cc30434)
mbed-os (da9464d103057f63064e49df258c1e5ca901c07c)

**Expected behavior:**
The example runs on the target without stopping on SW3 button press.

**Actual behavior**
The example runs on the target then stops running on SW3 button press.

**Steps to reproduce**
```
$ git clone https://github.com/ARMmbed/mbed-os-example-uvisor
$ cd mbed-os-example-uvisor
$ git checkout mbed-os-5.7.0-oob
$ mbed deploy
$ mbed compile -t GCC_ARM -m K64F -f
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-521

**Comment by alzix** [comment]
Please do not press SW3 button. It is not intended to be pressed as part of this example.
Unregistered interrupts will result in halting the program  https://github.com/ARMmbed/uvisor/blob/master/core/system/src/core_armv7m/virq.c#L400

**Comment by MarceloSalazar** [comment]
@alzix can you please help us to make this clear in the docs?
